Rework the benchmark runner and add option to test with node
Benchmark files are concatenated into one single JS file when testing
with node, since it only takes one script argument.  Note that all
benchmarks currently fail on node. See example below:

TypeError: undefined is not a function
    at ScalaJS.c.java︳lang︳String$.init︳︴ (richards/target/scala-2.10/richards.node.js:193735:127)
    at Object.ScalaJS.modules.java︳lang︳String (richards/target/scala-2.10/richards.node.js:193801:102)
    at ScalaJS.c.scala︳runtime︳ScalaRunTime$.init︳︴ (richards/target/scala-2.10/richards.node.js:177614:178)
    at Object.ScalaJS.modules.scala︳runtime︳ScalaRunTime (richards/target/scala-2.10/richards.node.js:177774:122)
    at ScalaJS.c.scala︳collection︳immutable︳HashMap.elemHashCode︴O︴I (richards/target/scala-2.10/richards.node.js:454433:26)
    at ScalaJS.c.scala︳collection︳immutable︳HashMap.computeHash︴O︴I (richards/target/scala-2.10/richards.node.js:454442:42)
    at ScalaJS.c.scala︳collection︳immutable︳HashMap.$plus︴Lscala︳Tuple2︴Lscala︳collection︳immutable︳HashMap (richards/target/scala-2.10/richards.node.js:454424:220)
    at ScalaJS.c.scala︳collection︳immutable︳HashMap.$plus︴Lscala︳Tuple2︴Lscala︳Tuple2︴Lscala︳collection︳Seq︴Lscala︳collection︳immutable︳HashMap (richards/target/scala-2.10/richards.node.js:454427:76)
    at ScalaJS.c.scala︳collection︳immutable︳Map$Map4.updated︴O︴O︴Lscala︳collection︳immutable︳Map (richards/target/scala-2.10/richards.node.js:462860:103)
    at ScalaJS.c.scala︳collection︳immutable︳Map$Map4.$plus︴Lscala︳Tuple2︴Lscala︳collection︳immutable︳Map (richards/target/scala-2.10/richards.node.js:462867:15)